Origin form changes
CoBrALab/ODC-Mouse-Forms pull request #50
Opened 2024-12-23 20:48 UTC by david-roper

closes issues #40 #42 

this pull requests adds

motherId now conditional if mother is known (same as how father id is dealt with)

fixed m83 type

added genotype as a separate question in origin form

new form can be seen [here ](https://playground.opendatacapture.org/?files=NobwRAxg9gdgLgU3mAXGA9AKgAQIM4A2AlvALQAmReAhgEYELYAOCATgGYIRxGxVzo8UVnFJRaAKy5w82TOgA6MJdBh442ENnIJ2JBAEk1cVgFcAtkg0BfbAF5s1AO7UiGouabC4ACgDk6GbwHgjoAG4AjOgAAlAsMOTUcNQQ1ExwpqyhQTyWpNBZ6CQ6AB4AdBJ4fgCUANwqsOqa2ABe2LYOzq7unt7%2BgabBluFRLVDk0QDMZQBM0yVFCQjllTX1yjDLXiLautSmBBo6eptG6maW8D4gStjYANbFKNh%2BAGIA8gBKALJ%2BADS3bAEagwADmpmooIQzz8SH%2BgOSoLwz2AfgAQkQRAALf4vb5QUx4BD-PzvVhEUEkPwAXQBMDuJEQrBg1AIzxu9LuuEoPFgzwidK52BZlhh33eAFUAMoAUQA%2Bl8DABxAwAOTlHx%2BfkB1kF2FUiHg7MBd0SiHe7Ax2ONnKFjwSMLNxL1QuBtAQbOwCjATuwUHY2FomLgWO9JvaLuw5gJRKlyxtQru9vIMPOJFB8NtXLC1HJILgMNY1EoUEziaBdA9MLjJTLibivLUCfLXrA31ZCG9z297YY3sjQu9rwQ5g7Xdbw9HfbA4bu1nDuvD0Cx3gMKc0s4eTxeabBdaFObzRpeJCYpjg%2B65bqrLwAwlAVzs11YiHpUo3sD53uleCyCNVtSzRcs2jQkEClExXBgZs7W3b1d1BftN0PIh827MAiQYbgkKzO5r09HsY0Yc4oJw8sG1-ZEN1wrkewADkmcd6MYsAB1osBbwAVgAdjRAAZdAADYACkmI4nj%2BKE0TWM3O5vU4gANV4AEEABExMUlT1Jkmi5LASYSgAFSVUg1LEgzjNM7S2L094QzYLtvTsrEHJnGj5yAyMoHs1gIKLEgYK5ZN0PIABPEUiAgMjEx0JgqOAb1QNjSCSG9WlNyyJZWB8M1qGqaiW2wV8cqSagyiS8CUvpOwatbZzXOqDlCq5LIMmZArmqTYpsHQhDos6lC0NbU9z365r8PQ%2BrWGwEjUrczr2lkxbdOwVrMnpGADgITcPKFYChQqpUkG80KWECrqHVbPqdPLQbj3gj1pDGvDKwItsiJmqrnr9H9GnO9iAAkRyIFpQtBGMxKB8wQbBiGbpbb0AagaNQfBwlIeRqBUbhmzWwAdSIAhyFIOBTs7VB8cJ4nSZYMN3IXSNaCgEp8TA-7gpeJmoAYEFLzuO6CxeIsSz5it3U9UlyUpFlEFkdhWGR3ASiZP9AyyBAdGmnw0WZqMiOqAB%2BQC9q81hNbXdntz8MKIogUXYvivwmZZoiaTYzLNZK5J8qaltX0-XKymd1miUapa7jW9rfc6jm-AQ0XbtzVDjz8EaL1x11XphMlNewAxVON5rdpbYvy0jjatp2hnw1odXNbJCkAo62DLut8LqGhu22IdlEneZkPiXSmiPbYL28ubxN-bHoP%2B-16OW3LifCtj%2BOM%2BzJOhrjx7uATxMJrqqWSD9ANa4QDXXLXu4KL%2Bpfmu9W8sVzBhZE%2BIgwjYbA%2BLoYQkmEIh8DEg-J%2B%2BBsCv3ftNL%2BTMixwD-gA%2BGC1WwyhgGECkUAxJIJQeDb6hVvQGF6CIMSeDthwGwQjMAwkUj3CEPSSBP8YHkjgehChEAqGwE-t-aBsC8CkPLE5HyYkpp0wQaXEuS0RFCkXptAg216aeXDN5FyrA0R1zYA3aWltW42w7pFe2CA4oom9Kfc%2BrA1FzSHmXJAntco%2ByWsVQORj66H2qrVPhijvRhxWhHBAbV6Tz2XnBDCJh0w8PXkeQW3o04hJeuLSaPklYq1ZGrM%2BmshFFzEUtSRldZEm3DNGHyABpGAUAnDQVvrHLRnddH6OwKiYOrtzGJhHtlaxt8irsGnnUsC9harsFZKHPxEjvHrVaRddcfduYIF5hnAWhZiy8F3mLG8uDZD2T1nE%2B4RSSkG1SaI3S4ivE%2BOFFk8sIj9pcjyYogeGixkVJ0d3PRjtOlEhJBctghTikwDdhlSxo8WkDLaR02eXSaoOF6QQIk2AABkkLtClXKgot5myYAeOaovf5QUAnXTXjM4aMAzwkPgS2feuDyDHz1mBOOay3HzUKvs5aC8hntSkTIk51csy9IKUi65jp26VPudU2pQLnkNMGVlMeNjdJ2LhU8xgILsBgv6eHNF4dY5cx5p86ZG8U7C3mRnYlYADArJcvKpIiiHhIu2TS3Z1qLGHOZVXOR7LTVsCuUvcpvK7mzh7jUvuLsKV-D8ByxR7ySlfNwk08Vt8pXJBnn6iFcqFWMGhbCmNQbEUfJRQyw56LRmpiCXubFWrBapzxeeBZiy3prjJRVSlabWA7MTPs-ZmTpGzlOZGKEmxoG-lVBYd0rBuUvE2uYftoscUlvxaLfefhVSkE7WwJIv5q2uwXDqPUEBiBWFUt41w4LAr4FyEkDWqlMiLr5NgAU4YSDnFMNwSivc8YuU2OAxwwoEBOHJRCqggZhD0icG4LER9Vluj%2BH6aa36tjeA1vKhW5hHD0mWAkggSTjHYBDN%2B9gwg4N4BXAcUl7p5WEwYKSoDUAgRQFBEVGQRUYCYdYKORsZQ84BlWRVIqctYPwfiWwVWDi2CgZIHRhjS7-RoeNXx6a1BZBOA9MhqTYnGDOwU5%2BxgqRLA0fY0rFg3BoMwMDIwDZHyyg0jXYCHQyRCZUXnjoPAEByS-VKX4QyRYWGyGoCphQChKVBmxDRoTZ6YCgacC5OJbhsAuFkFAv9AGgPGrdGBrjkGRDQbY-LRWIJuPMkSRJy8xAIBICJDCZSTAUguVIDMMoAAGS8PA4AMDFB9Ux9JXhYcLmcywUnMj4Bgk6C0VoQyBVjqodQuWs4vFUkeslPmQyXiyOwR0R6%2BvBhxKZzkFUayDatsN9O4Zp01lm7oGE63lhtfXQ%2BVc6555DcaDtrM077yPlu4M%2BbLxlwXdO4CdbVVNut226NmJeIPp%2BSggdl7fgvv%2BU%2Batq%2BPlgdNyu1tm7-2bykjiXDjV4Y5swgRb5KqH21tESOkUmm0IJ7XeMMjiWA9sBE5OiwUHR3CfHRJ-ju4MqftjL%2B5GadRCoOkprZGLHrYZWpLOcIc2l3wzk5G9zsbktc75wZy8cXbA1ys5Q44xupSEe-aR7LgH6IVHTT-tLJXTsjdNfVzj5RyTVFOI5zCLnu25dTWwDb4xZvrcW6cer15rAQ3a6l4jin%2BuUf4nWUis3fuA%2B%2B5x66nXnO9fO4N%2BHs1omBeY8Oy8P3A91d1oDw717Se7ty9eM66ahnQ2C6z4G8vMfocmp8vHoPuuQ-J5R2XuJ6fXbV7B3W3PDf53dtgL2kdbBC9%2BCdyXg3ROF0flH6O3vMIh8BYX2wNrDeczEDNL%2BKUEAXKjmeC0Mo4gpDcGuGZxblpltH7KE6Hw1Q9THZKLfpAFgfCol7M6F4k4Ow0kf4CG9iIBbK0GUAhA-ifg5qyA-nqOzqAWqpMjADAZ9kROjq-sOh-uGH4N8AxJeH4FxLxAJCJHgZpGpHgRZCZGQZGKjoooXNSAAZyDjmgaAeAdUJAY2NAQwXcIdMzmTOge-glFmH4EjCjLDISHgVDDDGjFUNQQTETCTGTHQVwWBhLrfqwewb%2BJwU-jjgXvAVABMiCBAdfH%2BMgQTk3kRGofmqCEYVAQQKYXcPnlynoQYUgWwcYVoYCP3hYSwVYTYRwXYcoRJk1vweYJgUIUAqwM-KAm-B-LQpwgwjIVgRgqgngbziIHgcwqwjQhwr-AkXgVNEoRobAB4YwT5O7pruoj4eSGCH4ZoQEXqCvo2GvgOqAcOv2hAdDEgZVmwYyA-koNYNUP0XUKxGACKAgKgGAMUMsGUDIGANYNSEAA&label=LYewrgzgpg%2BiBOBLA5ogdjAZg4Q)

2025-01-14 20:50 UTC, david-roper commented
@tulste I have added the new changes if you'd like to review it again, I have changed the link to the latest form. You can also access it [here](https://playground.opendatacapture.org/?files=NobwRAxg9gdgLgU3mAXGA9AKgAQIM4A2AlvALQAmReAhgEYELYAOCATgGYIRxGxVzo8UVnFJRaAKy5w82TOgA6MJdBh442ENnIJ2JBAEk1cVgFcAtkg0BfbAF5s1AO7UiGouabC4ACgDk6GbwHgjoAG4AjOgAAlAsMOTUcNQQ1ExwpqyhQTyWpNBZ6CQ6AB4AdBJ4fgCUANwqsOqa2ABe2LYOzq7unt7%2BgabBluFRLVDk0QDMZQBM0yVFCQjllTX1yjDLXiLautSmBBo6eptG6maW8D4gStjYANbFKNh%2BAGIA8gBKALJ%2BADS3bAEagwADmpmooIQzz8SH%2BgOSoLwz2AfgAQkQRAALf4vb5QUx4BD-PzvVhEUEkPwAXQBMDuJEQrBg1AIzxu9LuuEoPFgzwidK52BZlhh33eAFUAMoAUQA%2Bl8DABxAwAOTlHx%2BfkB1kF2FUiHg7MBd0SiHe7Ax2ONnKFjwSMLNxL1QuBtAQbOwCjATuwUHY2FomLgWO9JvaLuw5gJRKlyxtQru9vIMPOJFB8NtXLC1HJILgMNY1EoUEziaBdA9MLjJTLibivLUCfLXrA31ZCG9z297YY3sjQu9rwQ5g7Xdbw9HfbA4bu1nDuvD0Cx3gMKc0s4eTxeabBdaFObzRpeJCYpjg%2B65bqrLwAwlAVzs11YiHpUo3sD53uleCyCNVtSzRcs2jQkEClExXBgZs7W3b1d1BftN0PIh827MAiQYbgkKzO5r09HsY0YCCixIHDywbX9kQ3XCuR7AAOSZxwYpiwAHOiwFvABWAB2NEABl0AANgAKWYzjeIE4SxLYzc7m9LiAA1XgAQQAEXEpTVI02TaPksBJhKAAVJVSHU8TDJMsydPY-T3hDNgu29eysUcmdaPnIDIygBzWBIqCYK5ZN0PIABPEUiAgcjEx0JhqOAb1QNjSCyLAWlNyyJZWB8M1qGqGiW2wV8cqSagyiS8CUvpOwatbFy3OqDlCq5LIMmZArmqTYpsHQhDos6lC0NbU9z365r8PQ%2BrWGwc4oLDPShU8wqlpbVrMnpGADgITcVrnSMKqVJAfNClhAq6h1Wz63Ty0G494I9aQxrwysCLbIjsEOmBjpYJ6-R-Rozo4gAJEciBaULQRjcSQfMMGIah66W29IGoGjcHIcJaHUagdGEds1sQaZHH4cx1ACYQIncdJ-HvQAdSIAhyFIOATs7Mm6YZpmWZ%2B9zy12iNw1oKASnxMDAeCl4hagBgQUvO5boLF4ixLOWK3dT1SXJSkWUQWR2FYVHcBKJk-0DLIEB0aafDRYWoyI6oAH5AMW7zWEttdxe3PwwoiiBVdi%2BK-CFkWiJpdjMstkrknypqW1fT9crKYPRaJRq5Jain1o6zqJb8BDVZu3NUOPPwRovfHXRemEyUt7ADDU53mv5xb07W9rNoIbaPIXSNaHNy2yQpEhPYu73wuoWG-fYgOUSD4WU%2BJdLaIjtgo7y7PE3jtek-n%2B3Y8Ktv6X35rc-zivsyLoa84e7gC8TCa6q1kg-QDPuEAttzz7uSiAY3zrvVvFiXMDBZCfCIGENg2B%2BJ0GEEkYQRB8DiUAcA-A2AwEQOmtAoWRY4DwMQYjTq%2BkZQwDCBSKA4liGkMhr9Qq3oDC9BEOJeh2w4A0KRmAESKR7hCHpFg2BuDyT4PQpwiA3DYBQJgTgvBeA2Hlmcr5cSU15qEPaOnOc6dm4ZzahtLaO0e7hh8q5VgaJ%2B5sEHtrEe64x6%2B39ggOKKJvRvw-qwcxqUl7lhXtlXKMd07FUTk4geT9qq1XkUY70acFp3EPn-FsEt4ImHTLIi%2BR5FbejLkk566tJq%2BSNibVkZt36W2UU3DRrdM7t10d3Ly4Zoy%2BQANJfScNBGJucfYT0irY%2Bx2BUTJ1Du4xMni14%2BL0n40qO8Q5gXsLVdgrJU7HwGeUo%2Bajc5SxljAO%2B2AFaFmLLwDZD86GyAcnbHJ9xGkwAdsUlsmjVF6WiR3LufN9EgUMWwBeljHTj0np0wOvSwIklqUYhpUAmlhwykgSO3iYlFXYNvX5RIpkOBmQQeFAAyFF2gxkArYECppETmrRPmYmOJGEElgiSVs4aMAzysIIS2fZYA1wvztn82QWLWCXMeXpa5dzKmcpduGGZ9SznvJeG0r5087E-N3n8-pQpBmQsJdC2F0r4U1URbMhAeKD6LKhedKxqyECywrhSvwytdkV3pQYQ5rlsCCqMQ8M5FzebLTktynV9y9HVKzHa15REzqtM%2BR0gcM9ulzwmUSEkPrWA4vWbKqJ4LV4Ks3KM5I4yF4IttRq7AaKMWpqjTGrVHidWKqCl7M%2BajNmXxLmXDZasbx0PIEyiqedM0KOdXyxMmieWd1nPzYCQooSbBwb%2BVUFh3SsBFX4Ta5hx2qxNTW9iD8-CqlIIOtgSRfxNtDguHUeoIDECsGpCmrhkWBXwLkJIFs1KZA3XybAApwwkHOKYbgVFZ601cpsDBjhhQICcMy%2BFVBAzCHpE4NwWJn5HLdH8P000gNbG8BbW1BtzCOHpMsPJBACnOOwCGID7BhCobwCuA4jb3S2oZgwRtkGoBAigKCIqMgiowAI6wUcjYyh1wDEciqRU9YobQ7ktgpsAlsBgyQVj7HN3%2Blwza0T01qCyCcB6LDinZOMGDupgDjBUiWGY3xo2LBuBIdwYGRgpzgUwDKDSXdgIdDJAZtRY%2BOg8AQHJP9ZpfgjJFlEbIag2mFAKBbUGbEzHJO3pgDBpwrkcluGwC4WQ2DQPgcgzat0sHBMIZEEh3j%2BtDYgiE8yfJ8nLzEAgEgIkMIVJMBSK5UgMwygAAZLw8DgAwMU71XH0leIRxu-aoyGrwJkfAMEnQWitCGQKudVDqFK1XF4alL1MpCyGS8WR2COkveN4MOJbOcgqjWKbXsZvl3DEumsa3dAwgO8sPre6HyrnXMfabjRTtZiXfeR8b25VXZeMuR7d3AQHaqkd0eJ25tZLxO9fyVJIzreu0RGH6y9vf18kj0HVjweRiXVNbASPLsbZeC8vyVVAf7aIp9b60IN4veMBDm8fh02U%2B5s6cM8OXgHSOizsndw4XU%2Be8d179ONbMMQ425tcPfuOJVWzFHsH3ZPfDLT2b2P5ua1rvXAnMJhAK559hwJQ9mkC7B0L1XkP0SmOmvA7WWvJaW663r4nJjClmKCRjmEWOztq9x875xtu-BO-t0EvXbKY3u7%2B6br35v8QnLOf70Pce5dsreTTwXdOzcM5j-amTEu2e-b8Mn7dnJ%2Bv5uFank36eo8M9eEke1FmQWS8J34Uvlm9dRpT8bzHkf3tq5rzknPodG8wnb0XvagI13DtgKOmdbBw9%2BE9z383n110fmn7OofLwJ8RbX2wPrcuczEDNL%2BKUEBXKjmeC0Mo4gpDcGuHZrblodsX7KE6Hw1Q9Q3ZKM-pAFgfCol7M6C8JOB2DSO-oCP9iIB7K0GUAhG-lfh5qyG-nqHzs-gaiCEgUDojiDtAT-uYH-uGIzoxJeH4NxHxIJKJMQVpOpMQZZKZNQZGKSL5I3NSGAZyMTujtAbAdUPAY2IgawXcJzl9Czt-tOvgVmH4CjGjCTFUAwTDHDBjDIQQYTGwMTAocQfTIzMzKzMwfwfLmwFAZflwTwb%2BHwR-sTmHtAWgTAHAT-H%2BBgeTr5CnoYaSqCDYQgQQPYXcC3k0qgVANLIatYdwbYaYYCCPmLJwS4W4bwR4bofJl1iIb-glOIcgqwCAmguApAnwlIoIooeIZQmQsQaLiIMQSImIrwpInAjkcQVNDocYbACEWwb5L7gbhYhEeSGCFESYTEXqFvo2DvhOtAdOuOnAbDNYY1twYyG-koNYNUNMXUGxGACKAgKgGAMUMsGUDIGANYNSEAA&label=LYewrgzgpg%2BiBOBLA5ogdjAZg4Q) as well

2025-01-15 03:15 UTC, tulste approved these changes

2025-01-16 16:54 UTC, gdevenyi requested changes

2025-01-16 16:54 UTC, gdevenyi commented on lib/forms/CoBraLab-Mouse-Origin-Form/index.ts
>          "Other":"Other"
Can we condition a field to show up on Other that allows manual input

2025-01-20 20:56 UTC, david-roper commented on lib/forms/CoBraLab-Mouse-Origin-Form/index.ts
>          "Other":"Other"
Added other for genotype which brings up manual input, form link updated

2025-01-21 21:28 UTC, merged